import type { Metadata } from 'next';
import './index.css';

export const metadata: Metadata = {
  title: 'LernP ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {children}
        <div id="modal-root" />
      </body>
    </html>
  );
}
